services:
  online-tryout:
    container_name: "online-tryout"
    build: ./online-tryout
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - parsing-sheets-api
      - auth-api
  
  admin-app:
    container_name: "admin-app"
    build: ./admin-app
    ports:
      - "3001:3001"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - parsing-sheets-api
      - auth-api

  db-api:
    container_name: "db-api"
    build: ./db-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
      
  parsing-sheets-api:
    container_name: "parsing-sheets-api"
    build: ./parsing-sheets-api
    ports:
      - "8081:8081"
    restart: unless-stopped
    env_file:
      - .env

  auth-api:
    container_name: "auth-api"
    build: ./auth-api
    ports:
      - "8082:8082"
    restart: unless-stopped
    env_file:
      - .env

  tryout-api:
    container_name: "tryout-api"
    build: ./tryout-api
    ports:
      - "8083:8083"
    restart: unless-stopped
    env_file:
      - .env